export {
  ZendeskCustomerProfileValuesSchema,
  ZendeskGetCustomerProfileInputSchema,
  ZendeskGetCustomerProfileOutputSchema,
  ZendeskGetRequesterTicketsInputSchema,
  ZendeskGetTicketCustomFieldsInputSchema,
  ZendeskGetTicketCustomFieldsOutputSchema,
  ZendeskGetTicketInputSchema,
  ZendeskGetTicketOutputSchema,
  ZendeskListTicketFieldDefinitionsInputSchema,
  ZendeskListTicketFieldDefinitionsOutputSchema,
  ZendeskListVoicemailsInputSchema,
  ZendeskListVoicemailsOutputSchema,
  ZendeskReadVoicemailTranscriptChunkInputSchema,
  ZendeskReadVoicemailTranscriptChunkOutputSchema,
  ZendeskSearchSolvedTicketsInputSchema,
  ZendeskTicketCommentSchema,
  ZendeskTicketDetailSchema,
  ZendeskTicketFieldDefinitionSchema,
  ZendeskTicketFieldOptionSchema,
  ZendeskTicketSearchOutputSchema,
  ZendeskTicketSummarySchema,
  ZendeskTranscribeVoicemailInputSchema,
  ZendeskTranscribeVoicemailOutputSchema,
  ZendeskTranscriptionSourceSchema,
  ZendeskTranscriptSegmentSchema,
  ZendeskVoicemailArtifactSchema,
  ZendeskVoicemailHandleSchema,
  ZendeskVoicemailSchema,
  ZendeskVoicemailTranscriptArtifactSchema,
  ZendeskVoicemailTranscriptHandleSchema,
  ZendeskUpdateCustomerProfileInputSchema,
  ZendeskUpdateTicketCustomFieldsInputSchema,
  ZendeskVerifiedWriteOutputSchema,
  type ZendeskTicketDetail,
  type ZendeskTicketSummary,
  type ZendeskTranscribeVoicemailInput,
  type ZendeskTranscribeVoicemailOutput,
  type ZendeskVoicemail,
  type ZendeskVoicemailArtifact,
  type ZendeskVoicemailTranscriptArtifact,
} from "@resolve/contracts";
